name: github action test
run-name: ${{ github. actor }} has been added new commit.

on:
  push:
    branches-ignore:
      - 'main'

jobs:  
  build:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 19
        - name: 'install dependencies'
          working-directory: ./src
          run: npm ci
        - name: 'build'
          working-directory: ./src
          run: npm run build

          